name : 'terraform deploy'

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

env:
  BUCKET: vaishali-1998-bajpai
  TFSTATE_FILE: sona.tfstate
  DB_TABLE: vaishali_table
  

jobs:
  terraform:
    name: Terraform
    runs-on:  ubuntu-latest

    defaults:
      run:
        working-directory: ./Demo/example

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:      ${{ secrets.AWS_SESSION_TOKEN }} 

          aws-region: us-east-1      

      - name: Terraform Init
        id: init
        run:
          terraform init -reconfigure
         -backend-config="bucket=$BUCKET" 
         -backend-config="key=$TFSTATE_FILE" 
         -backend-config="dynamodb_table=$DB_TABLE"

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
